//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clip_Banco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaMonedaExtranjera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajaMonedaExtranjera()
        {
            this.CVU = new HashSet<CVU>();
        }
    
        public int idCajaMonedaExtranjera { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<int> Movimiento { get; set; }
        public string Detalle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVU> CVU { get; set; }
    }
}
