//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clip_Banco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVU
    {
        public string idCVU { get; set; }
        public string idUsuario { get; set; }
        public Nullable<int> idCajaMonedaLocal { get; set; }
        public Nullable<int> idCajaMonedaExtranjera { get; set; }
        public Nullable<int> idCajaCryptoMoneda { get; set; }
        public Nullable<int> idOperacion { get; set; }
    
        public virtual CajaCryptoMoneda CajaCryptoMoneda { get; set; }
        public virtual CajaMonedaExtranjera CajaMonedaExtranjera { get; set; }
        public virtual CajaMonedaLocal CajaMonedaLocal { get; set; }
        public virtual Operaciones Operaciones { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
