//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clip_Banco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public int idOperacion { get; set; }
        public string Tipo_Servicio { get; set; }
        public Nullable<double> Monto_Deuda { get; set; }
        public Nullable<int> idFactura { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Operaciones Operaciones { get; set; }
    }
}
